/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.*;

/*
 * AadharEnrollment.java
 *
 * Created on 15 Oct, 2018, 3:02:23 PM
 */

/**
 *
 * @author Mayand
 */
public class AadhaarEnrollment extends javax.swing.JFrame {

    /** Creates new form AadharEnrollment */
    public AadhaarEnrollment() {
        initComponents();
        setLocationRelativeTo(null);
        for(int i=01;i<=31;i++)
            cmbdd.addItem(""+i);
         for(int i=01;i<=12;i++)
             cmbmm.addItem(""+i);
         for(int i=2019;i>1900;i--)
            cmbyy.addItem(""+i);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtano = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbg1 = new javax.swing.JRadioButton();
        rbg2 = new javax.swing.JRadioButton();
        rbg3 = new javax.swing.JRadioButton();
        txtfname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taadd = new javax.swing.JTextArea();
        txtpin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmno = new javax.swing.JTextField();
        enroll = new javax.swing.JButton();
        back = new javax.swing.JButton();
        cmbdd = new javax.swing.JComboBox();
        cmbmm = new javax.swing.JComboBox();
        cmbyy = new javax.swing.JComboBox();
        reset = new javax.swing.JButton();
        tnc = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/320px-Aadhaar_Logo.svg.png"))); // NOI18N
        jLabel9.setText("label");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 173, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aadhaar Enrollment"));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Aadhaar Number");

        txtano.setText("000000000000");
        txtano.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtanoCaretUpdate(evt);
            }
        });
        txtano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtanoFocusGained(evt);
            }
        });

        txtname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtnameCaretUpdate(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Gender");

        buttonGroup1.add(rbg1);
        rbg1.setText("Male");
        rbg1.setOpaque(false);

        buttonGroup1.add(rbg2);
        rbg2.setText("Female");
        rbg2.setOpaque(false);

        buttonGroup1.add(rbg3);
        rbg3.setText("Others");
        rbg3.setOpaque(false);

        txtfname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtfnameCaretUpdate(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Date of Birth");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Father's Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Address");

        taadd.setColumns(20);
        taadd.setRows(5);
        taadd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                taaddCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(taadd);

        txtpin.setText("000000");
        txtpin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtpinCaretUpdate(evt);
            }
        });
        txtpin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpinFocusGained(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("PIN CODE");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Mobile No.");

        txtmno.setText("0000000000");
        txtmno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtmnoCaretUpdate(evt);
            }
        });
        txtmno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmnoFocusGained(evt);
            }
        });

        enroll.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        enroll.setText("Enroll");
        enroll.setBorder(new javax.swing.border.MatteBorder(null));
        enroll.setEnabled(false);
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        back.setText("Back");
        back.setBorder(new javax.swing.border.MatteBorder(null));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        cmbdd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        cmbdd.setToolTipText("DD");

        cmbmm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        cmbmm.setToolTipText("MM");
        cmbmm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmmItemStateChanged(evt);
            }
        });

        cmbyy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        cmbyy.setToolTipText("YYYY");
        cmbyy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbyyItemStateChanged(evt);
            }
        });

        reset.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(new javax.swing.border.MatteBorder(null));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        tnc.setText("I confirm that all the given data are correct according to best of my Knowledge. ");
        tnc.setOpaque(false);
        tnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpin, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtmno, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbg1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbg2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(rbg3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbdd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbmm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(cmbyy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tnc)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtano, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtfname, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbg1)
                        .addComponent(rbg2))
                    .addComponent(rbg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbyy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(tnc)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtano)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addGap(105, 105, 105)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(409, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 620));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label.png"))); // NOI18N
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 500, 130));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Aadhaar Enrollment");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 170, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/50-Beautiful-and-Minimalist-Presentation-Backgrounds-026.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
setReset();
}//GEN-LAST:event_resetActionPerformed

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed

        
        long ano=Long.parseLong(txtano.getText());      //Aadhaar Number ---- TextField
        
        String name=txtname.getText();                  //Applicant Name ---- TextField
        
        String gender=null;                             //Gender ---- RadioButton
            if(rbg1.isSelected()==true)
                gender="M";
            if(rbg2.isSelected()==true)
                gender="F";
            if(rbg3.isSelected()==true)
                gender="O";
            
        String fname=txtfname.getText();                //Applicant's Father Name ---- TextField

        String dob=cmbyy.getSelectedItem()+"-"+
                cmbmm.getSelectedItem()+"-"+cmbdd.getSelectedItem(); //Date of Birth ---- ComboBox
        
        String add=taadd.getText();                     //Address ---- TextField
        
        int pin=Integer.parseInt(txtpin.getText());     //PinCode ---- TextField
        
        long mno=Long.parseLong(txtmno.getText());      //Mobile Number ---- TextField
        String message1=null;
        String message2=null;
        String message3=null;
        String message4=null;
        String message5=null;
        String message6=null;
        String message7=null;
        String message8=null;
        String message9=null;
        String message10=null;
        String message11=null;
        String a=txtano.getText();
        String m=txtmno.getText();
        String p=txtpin.getText();
        String a1="000000000000";
        String m1="0000000000";
        String p1="000000";
if((name.isEmpty()||fname.isEmpty()||dob.isEmpty()||gender.isEmpty()||add.isEmpty())||a.length()!=12||a.equals(a1)||m.length()!=10||m.equals(m1)||p.length()!=6||p.equals(p1))
{
    if(a.length()!=12)
        message1="Aadhaar No. should be 12 digits.";
    else
        message1="";
    
    if(name.isEmpty())
        message2="Name not Entred";
    else
        message2="";
    
    if(fname.isEmpty())
        message3="Father's Name not Entred";
    else
        message3="";
    
    if(dob.isEmpty())
        message4="DOB not Selected";
    else
        message4="";
    
    if(add.isEmpty())
        message5="Address not Entred";
    else
        message5="";
    
    if(gender==null)
        message6="Gender not Selected";
    else
        message6="";
    
    if(m.length()!=10)
        message7="Mobile no. should be 10 digits";
    else
        message7="";
    
    if(p.length()!=6)
        message8="Pin should be 6 digits";
    else
        message8="";
    
    if(p.equals(p1))
        message9="Enter PinCode";
    else
        message9="";
    
    if(m.equals(m1))
        message10="Enter Mobile Number";
    else
        message10="";
    
    if(a.equals(a1))
        message11="Enter Aadhaar Number";
    else
        message11="";
    
JOptionPane.showMessageDialog(this,"Error !"+'\n'+message1+'\n'+message2+'\n'+message3+'\n'+message4+'\n'+message5+'\n'+message6+'\n'+message7+'\n'+message8+'\n'+message9+'\n'+message10+'\n'+message11);
}   
else
{
try
        {
          callcon cc=new callcon();
          Statement stmt=cc.callcon().createStatement();
          stmt.executeUpdate("INSERT INTO aadhaar VALUES("+ano+",'"+name+"','"+gender+"','"+fname+"','"+dob+"','"+add+"',"+pin+","+mno+");");
          cc.callcon().close();
          stmt.close();
          JOptionPane.showMessageDialog(null,"Record Inserted...");
          setReset();
         }
        catch(Exception e)
        {
 JOptionPane.showMessageDialog(null,e.toString());
        }
}
}//GEN-LAST:event_enrollActionPerformed
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    MainForm n= new MainForm();
     n.setVisible(true);
     this.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_backActionPerformed

    private void tncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tncActionPerformed
    if(tnc.isSelected()==true)
        enroll.setEnabled(true);
    else
        enroll.setEnabled(false);
    }//GEN-LAST:event_tncActionPerformed

    private void txtanoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtanoCaretUpdate
    if(txtano.getText().length()!=12)
        txtano.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        txtano.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtanoCaretUpdate

    private void txtnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtnameCaretUpdate
    if(txtname.getText().isEmpty())
        txtname.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        txtname.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtnameCaretUpdate

    private void txtfnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtfnameCaretUpdate
    if(txtfname.getText().isEmpty())
        txtfname.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        txtfname.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtfnameCaretUpdate

    private void taaddCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_taaddCaretUpdate
    if(taadd.getText().isEmpty())
        taadd.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        taadd.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_taaddCaretUpdate

    private void txtpinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtpinCaretUpdate
    if(txtpin.getText().isEmpty())
        txtpin.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        txtpin.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtpinCaretUpdate

    private void txtmnoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtmnoCaretUpdate
    if(txtmno.getText().isEmpty())
        txtmno.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        txtmno.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtmnoCaretUpdate

    private void txtanoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtanoFocusGained
    if(txtano.getText().equals("000000000000"))
        txtano.setText(null);
    }//GEN-LAST:event_txtanoFocusGained

    private void txtpinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpinFocusGained
    if(txtpin.getText().equals("000000"))
        txtpin.setText(null);
    }//GEN-LAST:event_txtpinFocusGained

    private void txtmnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmnoFocusGained
    if(txtmno.getText().equals("0000000000"))
        txtmno.setText(null);
    }//GEN-LAST:event_txtmnoFocusGained

    private void cmbmmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmmItemStateChanged
       if(cmbdd.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"Please Select Date First!!!");
        }
    }//GEN-LAST:event_cmbmmItemStateChanged

    private void cmbyyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbyyItemStateChanged
       if(cmbmm.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"Please Select Month First!!!");
        }
    }//GEN-LAST:event_cmbyyItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AadhaarEnrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbdd;
    private javax.swing.JComboBox cmbmm;
    private javax.swing.JComboBox cmbyy;
    private javax.swing.JButton enroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbg1;
    private javax.swing.JRadioButton rbg2;
    private javax.swing.JRadioButton rbg3;
    private javax.swing.JButton reset;
    private javax.swing.JTextArea taadd;
    private javax.swing.JCheckBox tnc;
    private javax.swing.JTextField txtano;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtmno;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpin;
    // End of variables declaration//GEN-END:variables

    void setReset()
    {
        txtano.setText("000000000000");
        txtname.setText(null);
        txtfname.setText(null);
        taadd.setText(null);
        txtpin.setText("000000");
        txtmno.setText("0000000000");
        rbg1.setSelected(false);
        rbg2.setSelected(false);
        rbg3.setSelected(false);
        cmbyy.setSelectedIndex(0);
        cmbmm.setSelectedIndex(0);
        cmbdd.setSelectedIndex(0);
        tnc.setSelected(false);
        enroll.setEnabled(false);
        txtano.setBorder(BorderFactory.createLineBorder(Color.gray));
        txtname.setBorder(BorderFactory.createLineBorder(Color.gray));
        txtfname.setBorder(BorderFactory.createLineBorder(Color.gray));
        txtpin.setBorder(BorderFactory.createLineBorder(Color.gray));
        txtmno.setBorder(BorderFactory.createLineBorder(Color.gray));
        taadd.setBorder(BorderFactory.createLineBorder(Color.gray));
    }
}
