/*
 * ForNewUser.java
 *
 * Created on 15 Oct, 2018, 2:39:52 PM
 */
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Mayand
 */
public class ForNewUser extends javax.swing.JFrame {

    /** Creates new form ForNewUser */
    public ForNewUser() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtuid = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpwd = new javax.swing.JPasswordField();
        txtpwd1 = new javax.swing.JPasswordField();
        cbpwd = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lbluid = new javax.swing.JLabel();
        lbluid1 = new javax.swing.JLabel();
        lblpwd = new javax.swing.JLabel();
        lblpwd1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.setBorder(new javax.swing.border.MatteBorder(null));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 96, 37));

        reset.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(new javax.swing.border.MatteBorder(null));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 102, 37));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 238, 163, 29));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("User ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 182, 163, 28));

        txtuid.setText("Enter Username");
        txtuid.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtuidCaretUpdate(evt);
            }
        });
        txtuid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuidFocusGained(evt);
            }
        });
        getContentPane().add(txtuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 183, 330, 28));

        cancel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.MatteBorder(null));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 102, 37));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Re-Type Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 300, 163, 29));

        txtpwd.setText("1234567890");
        txtpwd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtpwdCaretUpdate(evt);
            }
        });
        txtpwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpwdFocusGained(evt);
            }
        });
        getContentPane().add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 238, 330, 29));

        txtpwd1.setText("1234567890");
        txtpwd1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtpwd1CaretUpdate(evt);
            }
        });
        txtpwd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpwd1FocusGained(evt);
            }
        });
        getContentPane().add(txtpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 301, 330, 29));

        cbpwd.setText("Show Password");
        cbpwd.setOpaque(false);
        cbpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpwdActionPerformed(evt);
            }
        });
        getContentPane().add(cbpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 164, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/320px-Aadhaar_Logo.svg.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("Create Account");
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 140, 30));
        getContentPane().add(lbluid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, 20));
        getContentPane().add(lbluid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, 20));
        getContentPane().add(lblpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 280, 20));
        getContentPane().add(lblpwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 230, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    String uid=txtuid.getText();
    String pwd=txtpwd.getText();
    String pwd1=txtpwd1.getText();
    String u=null;

    if(uid.equals("Enter Username") || uid.isEmpty())
        JOptionPane.showMessageDialog(this,"Please Enter Username");
    else
    {
        try
        {
          callcon cc=new callcon();
          Statement stmt=cc.callcon().createStatement();
          String qry="SELECT * FROM login; ";
          ResultSet rs=stmt.executeQuery(qry);
          while(rs.next())
          {
              u=rs.getString(1);
          }
          rs.close();
          cc.callcon().close();
          stmt.close();
        }
        catch(Exception e1)
        {
          JOptionPane.showMessageDialog(null,e1.toString());
        }     
            if(pwd.equals(pwd1))
        {
            try
            {
                callcon cc=new callcon();
                Statement stmt=cc.callcon().createStatement();
                String qry="INSERT INTO login values('"+uid+"','"+pwd+"') ";
                stmt.executeUpdate(qry);
                cc.callcon().close();
                JOptionPane.showMessageDialog(this,"New User Created Successfully.");
                txtuid.setText("");
                txtpwd.setText("");
                txtpwd1.setText("");
                LoginForm lf= new LoginForm();
                lf.setVisible(true);
                this.setVisible(false);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.toString());
            }

        }
        else
        {
          JOptionPane.showMessageDialog(this,"Password mis-match error!!");
        }
    }
    }//GEN-LAST:event_submitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        txtuid.setText("Enter Username");
        txtpwd.setText("1234567890");
        txtpwd1.setText("1234567890");
        cbpwd.setSelected(false);
    }//GEN-LAST:event_resetActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
      LoginForm lf= new LoginForm();
      lf.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void cbpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpwdActionPerformed
        if(cbpwd.isSelected()==true)
        {
            txtpwd.setEchoChar((char)0);
            txtpwd1.setEchoChar((char)0);
        }
        else
        {
            txtpwd.setEchoChar('\u25cf');
            txtpwd1.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_cbpwdActionPerformed

    private void txtuidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuidFocusGained
    txtuid.setText(null);
    }//GEN-LAST:event_txtuidFocusGained

    private void txtpwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpwdFocusGained
    txtpwd.setText(null);  
    }//GEN-LAST:event_txtpwdFocusGained

    private void txtpwd1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpwd1FocusGained
    txtpwd1.setText(null); 
    }//GEN-LAST:event_txtpwd1FocusGained

    private void txtuidCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtuidCaretUpdate
    String uid=txtuid.getText();
    if(uid.isEmpty())
        lbluid.setText("Field Required");
    else
        lbluid.setText(null);
    }//GEN-LAST:event_txtuidCaretUpdate

    private void txtpwdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtpwdCaretUpdate
        String pwd=txtpwd.getText();
        if(pwd.length()<6)
            lblpwd.setText("Pwd must be in between 6-40");
        else
            lblpwd.setText(null);       
    }//GEN-LAST:event_txtpwdCaretUpdate

    private void txtpwd1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtpwd1CaretUpdate
    String pwd= new String(txtpwd.getText());
    String pwd1= new String(txtpwd1.getText());
    if(pwd.equals(pwd1)==false)
        lblpwd1.setText("Password mis-match");
    else
        lblpwd1.setText(null);
    }//GEN-LAST:event_txtpwd1CaretUpdate
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForNewUser().setVisible(true);
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox cbpwd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblpwd;
    private javax.swing.JLabel lblpwd1;
    private javax.swing.JLabel lbluid;
    private javax.swing.JLabel lbluid1;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JPasswordField txtpwd1;
    private javax.swing.JTextField txtuid;
    // End of variables declaration//GEN-END:variables

}
