import java.util.*;
import java.sql.*;
import javax.swing.*;
import java.awt.Color;
/*
 * LoginForm.java
 *
 * Created on 15 Oct, 2018, 2:39:36 PM
 */

/**
 *
 * @author Mayand
 */
public class LoginForm extends javax.swing.JFrame {

    /** Creates new form LoginForm */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuid = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        txtpwd = new javax.swing.JPasswordField();
        cbpwd = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("AADHAR RECORD KEEPING SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 445, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("User ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 174, 203, 28));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 208, 106, 32));

        txtuid.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtuidCaretUpdate(evt);
            }
        });
        getContentPane().add(txtuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 174, 283, 28));

        login.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        login.setText("Login");
        login.setBorder(new javax.swing.border.MatteBorder(null));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 96, 39));

        cancel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.MatteBorder(null));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 102, 39));

        txtpwd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtpwdCaretUpdate(evt);
            }
        });
        getContentPane().add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 212, 283, 26));

        cbpwd.setText("Show Password");
        cbpwd.setOpaque(false);
        cbpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpwdActionPerformed(evt);
            }
        });
        getContentPane().add(cbpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 242, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/320px-Aadhaar_Logo.svg.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 182, 121));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 470, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
     String u=txtuid.getText();
     String q=null,w=null;
     
          
    if(u.isEmpty())
    {
        JOptionPane.showMessageDialog(this,"Enter Username");
    }
    else
    {        
    try
     {
         callcon cc=new callcon();
         Statement stmt=cc.callcon().createStatement();
         String qry="SELECT * FROM login WHERE uid= '"+u+"' ";
         ResultSet rs=stmt.executeQuery(qry);

        while(rs.next())
        {
        q=rs.getString(1);
        w=rs.getString(2);
        }
     }
    catch( Exception e)
     {
         JOptionPane.showMessageDialog(this,e.toString());
     }
            
    try{   
            if(txtuid.getText().equals(q) && txtpwd.getText().equals(w))
            {
                JOptionPane.showMessageDialog(null, " Welcome to Aadhaar Record Keeping System");
                this.setVisible(false);
                MainForm m= new MainForm();
                m.setVisible(true);
                this.setVisible(false);
            }
            else
            {
            JOptionPane.showMessageDialog(null, "Invalid Login...");
            System.out.print("null");
            txtuid.setText(null);
            txtpwd.setText(null);
            txtuid.setBorder(BorderFactory.createLineBorder(Color.gray));
            txtpwd.setBorder(BorderFactory.createLineBorder(Color.gray));
            }
    }
    catch( Exception e){
        System.out.println(e);
    }
    } 
    }//GEN-LAST:event_loginActionPerformed

    private void cbpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpwdActionPerformed
     if(cbpwd.isSelected()==true)
     {
         txtpwd.setEchoChar((char)0);
     }
     else
     {
         txtpwd.setEchoChar('*');
     }
}//GEN-LAST:event_cbpwdActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
Home h=new Home();
h.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void txtuidCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtuidCaretUpdate
    if(txtuid.getText().isEmpty())
        txtuid.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        txtuid.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtuidCaretUpdate

    private void txtpwdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtpwdCaretUpdate
    if(txtpwd.getText().isEmpty())
        txtpwd.setBorder(BorderFactory.createLineBorder(Color.red));
    else
        txtpwd.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtpwdCaretUpdate

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox cbpwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtuid;
    // End of variables declaration//GEN-END:variables

}
